---
services:
  # ---
  redis:
    image: redis:bookworm
    restart: always
    networks:
    - backend
    ports:
    - "6379:6379/tcp"

  # ---
  front:
    image: hub.intraclear.com/cds-runtime-nginx:0.0.2-beta5
    # build:
    #   context: ./docker
    #   args:
    #     CPU_ARCH: ${CPU_ARCH}
    command: ["nginx"]
    restart: always
    depends_on:
    - redis
    volumes:
    - /app_files/####ENV_NAME####/rep/logs/nginx:/var/lib/www-data/log/nginx
    - /app_files/####ENV_NAME####/rep/logs/php:/var/lib/www-data/log/php
    - /app_files/####ENV_NAME####/rep/logs/supervisor:/var/lib/www-data/log/supervisor
    - /app_files/####ENV_NAME####/rep/logs/laravel:/var/lib/www-data/log/laravel

    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 512M
    #     reservations:
    #       cpus: '1'
    #       memory: 512M
    ports:
    - "####ENV_HTTP_PORT####:443"
    networks:
    - backend
    - frontend
    ####DB_EXTRA_HOST####

networks:
  frontend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: ####ENV_NAME####-rep-fi
  backend:
    driver: bridge
    internal: true
    driver_opts:
      com.docker.network.bridge.name: ####ENV_NAME####-rep-bi
  ####DB_NETWORK####

...
